package vaccinationbookingsystem.GUI.RegistrationUI;


import vaccinationbookingsystem.Admin;
import vaccinationbookingsystem.Customer;
import vaccinationbookingsystem.Person;
import vaccinationbookingsystem.Database.databaseController;
import vaccinationbookingsystem.helper.Helper;



/**
 *
 * @author Omar essam
 */
public class Registration extends javax.swing.JFrame {

    private Person person;
    
    /**
     * Creates new form Reigsteration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        fullName = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        age = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        passportNo = new javax.swing.JLabel();
        passportField = new javax.swing.JTextField();
        phoneNo = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        homePageIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vaccination Booking System");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // formMouseClicked(evt);
            }
        });

        fullName.setText("Full Name: ");



        age.setText("Age:");



        passportNo.setText("Passport No:");



        phoneNo.setText("Phone  No:");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        homePageIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vaccinationbookingsystem/Assets/home-icon.png"))); // NOI18N
        homePageIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homePageIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homePageIconMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Registration form");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(passportNo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passportField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(phoneNo)
                                .addGap(18, 18, 18)
                                .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(homePageIcon)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(fullName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(saveButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homePageIcon)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(fullName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passportField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passportNo)
                    .addComponent(age))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNo))
                .addGap(34, 34, 34)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * if the user click on the home page icon, this function will redirect the user to the main menu
     * @param evt
     */
    private void homePageIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePageIconMousePressed
        Helper.redirectToHomePage();
        dispose();
    }//GEN-LAST:event_homePageIconMousePressed

    /**
     *  handle the registeration after the user clicked on the save button, and the save the data in the datbase 
     * @param evt
     */
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_saveButtonActionPerformed
        String name = nameField.getText().trim();
        int age = Integer.parseInt(ageField.getText().trim());
        String phone = phoneField.getText().trim();
        String ID = passportField.getText().trim();
        String personType;
        try {
            if (ID.contains("admin")) {   // determine the person type based on the ID no
                person = new Admin(name, age, phone, ID);
                personType = "admin";
            } else {
                person = new Customer(name, age, phone, ID);
                personType = "customer";
            }

            if (personType.equals("admin")) {  // store the the person data in the admin table if the user is an admin
                databaseController.insertToTable(databaseController.adminTableQuery(person.getName(),
                        person.getAge(), person.getPhoneNumber(),
                        person.getPassprotNumber()));
            } else { // store the the person data in the customer table if the user is an customer
                databaseController.insertToTable(databaseController.cusotmerTableQuery(person.getName(),
                person.getAge(), person.getPhoneNumber(),
                person.getPassprotNumber()));
                
            }
            Helper.showDialogMessage("Successfully registered", "info");
            new Login().setVisible(true);
            dispose();
        } catch (NumberFormatException e) {
            Helper.showDialogMessage("please enter a valid age", "error");
        } catch (Exception e) {
            Helper.showDialogMessage("There is an error, please try again", "error");
        }
    }// GEN-LAST:event_saveButtonActionPerformed




    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel fullName;
    private javax.swing.JLabel homePageIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField passportField;
    private javax.swing.JLabel passportNo;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneNo;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
