
package vaccinationbookingsystem.GUI;
import vaccinationbookingsystem.GUI.CustomerUI.CustomerVaccine;
import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;

import vaccinationbookingsystem.*;

/**
 *
 * @author Omar essam
 */
public class customerAppoitment extends javax.swing.JFrame {
    DefaultTableModel model;
    private String customerID;
    /**
     * Creates new form customerAppoitment
     */
    public customerAppoitment() {
        initComponents();
    }
    public customerAppoitment(String customerID) {
        this.customerID = customerID;
        initComponents();
        Customer customer = new Customer();
        ArrayList<Appoinment> appoitmetnList = customer.getAppointmentData(customerID);
        model = new DefaultTableModel(); 
        jTable1.setModel(model);
        String[] columnsName = { "date", "vaccine name",  "reference number" };  // set the table heading 
        for (String name : columnsName) {
            model.addColumn(name);
        }


        for (Appoinment appoinment : appoitmetnList) {
            model.addRow(new Object[] {
                    appoinment.getDate(),
                    appoinment.getVaccine().getName(),
                    appoinment.getReferenceNo()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        goBackIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        goBackIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vaccinationbookingsystem/Assets/back-icon.png"))); // NOI18N
        goBackIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goBackIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goBackIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(goBackIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    /**
     * if the user clicked on the back arrow icon, this fucntion is resposible to redirect the user to the pervious page
     * @param evt
     */
    private void goBackIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackIconMouseClicked
        new CustomerVaccine(customerID).setVisible(true);
        dispose();
    }//GEN-LAST:event_goBackIconMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel goBackIcon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
